/* ------------------------------------------------------------------
   Bengal Planting Atlas : botanical database
   ------------------------------------------------------------------
   Each record is one species with a normalised tolerance vector x_ij
   (equation 4 of the framework) expressed as capacities on a 0..1
   scale, plus range matches for pH and salinity.

   Tolerance vector order (tol):
     [ flood, heat, drought, pHmin, pHmax, wlog, ECmin, ECmax, slope, frost ]
       flood   tolerance of standing water and short submergence
       heat    tolerance of pre-monsoon heat index (1 = 46 C and above)
       drought tolerance of dry-season root-zone deficit (1 = laterite upland)
       pH      tolerated topsoil pH range
       wlog    anaerobic root survival in saturated clay
       EC      tolerated soil salinity range, dS per m (min above 0 = halophyte)
       slope   root anchoring on slopes (1 = steep hill)
       frost   cold hardiness (1 = frost hardy, 0 = strictly tropical)

   Extras
     apti  [representative, low, high] Air Pollution Tolerance Index,
           literature-derived from Indian urban studies (Singh and Rao
           method). Classes follow Prajapati and Tripathi 2008:
           below 12 sensitive, 12 to 16 intermediate, 17 and above tolerant.
           null = not reported in literature.
     dust  particulate capture class H / M / L after the CPCB compilation
           of dust-capturing species; null = not assessed.
     r     mature canopy radius, m (shrubs: crown radius; ground: n/a)
     h     height at maturity, m
     dbh   diameter at breast height at maturity age, cm (trees)
     wd    basic wood density, g per cm3 (Global Wood Density Database)
     mat   years to the maturity size above
     bio   mature dry biomass, kg per plant (shrubs) or kg per m2 (ground)
     nfix  nitrogen fixing
     hab   'tidal' = obligate tidal mangrove, gated on tidal sites
     status native | naturalised | exotic (exotic species are screened,
           never recommended; they are kept so the engine can show why)
------------------------------------------------------------------ */

function SP(st, id, sci, bn, en, fam, status, tol, x) {
  return Object.assign({ st, id, sci, bn, en, fam, status,
    tol: { flood: tol[0], heat: tol[1], drought: tol[2], ph: [tol[3], tol[4]], wlog: tol[5], ec: [tol[6], tol[7]], slope: tol[8], frost: tol[9] },
    apti: null, dust: null, nfix: false, hab: null, roles: [], note: '' }, x);
}

const SPECIES = [
  /* =========================== TREES =========================== */
  SP('tree','hijal','Barringtonia acutangula','হিজল (Hijal)','Indian oak, Freshwater mangrove','Lecythidaceae','native',
    [1.0,0.75,0.3,5.5,8.0,1.0,0,2.5,0.3,0.2],
    { apti:[13,11,15], dust:'M', r:5, h:10, dbh:35, wd:0.55, mat:20, roles:['canopy','riparian','wetland'],
      note:'Survives months of root submergence; lateral root plate stabilises alluvial banks. Primary canopy of the framework case study.' }),
  SP('tree','arjun','Terminalia arjuna','অর্জুন (Arjun)','Arjuna','Combretaceae','native',
    [0.85,0.85,0.8,6.0,8.2,0.8,0,2.5,0.6,0.3],
    { apti:[18,14,22], dust:'H', r:9, h:20, dbh:55, wd:0.72, mat:30, roles:['canopy','riparian','pollution'],
      note:'Buttressed riparian giant; deep and lateral roots hold levees. Tolerant APTI class, listed among CPCB dust-capturing species.' }),
  SP('tree','karanja','Pongamia pinnata','করঞ্জ (Karanja)','Indian beech, Pongam','Fabaceae','native',
    [0.7,0.95,0.9,5.5,8.5,0.7,0,5.0,0.5,0.2],
    { apti:[16,13,20], dust:'H', r:6, h:14, dbh:40, wd:0.65, mat:20, nfix:true, roles:['understory','edge','nfix','pollution'],
      note:'Nitrogen fixer for degraded urban soils; tolerates brackish water and heat. Understory and edge species of the case study.' }),
  SP('tree','jam','Syzygium cumini','জাম (Jam)','Jamun, Java plum','Myrtaceae','native',
    [0.7,0.85,0.7,5.5,8.0,0.7,0,2.5,0.5,0.3],
    { apti:[17,15,20], dust:'H', r:8, h:20, dbh:50, wd:0.70, mat:25, roles:['canopy','fruit','pollution'],
      note:'Dense evergreen crown; tolerates seasonal waterlogging on deltaic clay. Reliable urban avenue tree.' }),
  SP('tree','kadam','Neolamarckia cadamba','কদম (Kadam)','Kadam, Burflower tree','Rubiaceae','native',
    [0.6,0.75,0.4,5.5,7.5,0.5,0,1.5,0.4,0.2],
    { apti:[14,12,17], dust:'M', r:7, h:22, dbh:50, wd:0.38, mat:15, roles:['canopy','fast'],
      note:'Fast pioneer of moist alluvium; needs a free root run and dislikes stagnant clay.' }),
  SP('tree','chhatim','Alstonia scholaris','ছাতিম (Chhatim)','Devil tree, Blackboard tree','Apocynaceae','native',
    [0.5,0.8,0.7,5.5,8.0,0.5,0,2.0,0.5,0.25],
    { apti:[18,15,25], dust:'H', r:7, h:22, dbh:50, wd:0.38, mat:20, roles:['canopy','pollution','shade'],
      note:'Whorled evergreen canopy, high APTI, widely used along Kolkata roads; avoid permanently ponded pits.' }),
  SP('tree','bot','Ficus benghalensis','বট (Bot)','Banyan','Moraceae','native',
    [0.5,0.95,0.9,5.5,8.5,0.4,0,3.0,0.6,0.3],
    { apti:[25,20,33], dust:'H', r:15, h:20, dbh:120, wd:0.45, mat:40, roles:['canopy','pollution','cultural','carbon'],
      note:'Highest APTI in the database and the largest carbon stock per stem; needs 30 m clear radius at maturity.' }),
  SP('tree','peepal','Ficus religiosa','অশ্বত্থ (Ashwattha)','Peepal, Sacred fig','Moraceae','native',
    [0.5,0.95,0.9,5.5,8.5,0.4,0,3.0,0.6,0.3],
    { apti:[21,17,26], dust:'H', r:12, h:20, dbh:90, wd:0.45, mat:35, roles:['canopy','pollution','cultural','carbon'],
      note:'Tolerant APTI class; aggressive roots, keep clear of foundations and drains.' }),
  SP('tree','dumur','Ficus racemosa','যজ্ঞডুমুর (Jagyadumur)','Cluster fig','Moraceae','native',
    [0.8,0.85,0.6,5.5,8.0,0.7,0,2.5,0.5,0.25],
    { apti:[17,15,20], dust:'H', r:8, h:16, dbh:50, wd:0.42, mat:20, roles:['canopy','riparian','wildlife'],
      note:'Riverbank fig, fruit for birds and bats; tolerates flooding and clay.' }),
  SP('tree','neem','Azadirachta indica','নিম (Neem)','Neem','Meliaceae','native',
    [0.2,1.0,1.0,6.0,8.5,0.15,0,4.0,0.6,0.2],
    { apti:[19,14,24], dust:'H', r:8, h:15, dbh:45, wd:0.68, mat:25, roles:['canopy','pollution','medicinal','drought'],
      note:'Heat and drought proof, tolerant APTI class, but dies in waterlogged clay. Ideal for laterite and coal-belt towns.' }),
  SP('tree','mahua','Madhuca longifolia','মহুয়া (Mahua)','Mahua, Butter tree','Sapotaceae','native',
    [0.2,1.0,1.0,5.5,7.5,0.2,0,2.0,0.7,0.35],
    { apti:[14,12,16], dust:'M', r:9, h:16, dbh:60, wd:0.86, mat:35, roles:['canopy','livelihood','drought','carbon'],
      note:'Keystone of the Rarh and Chhota Nagpur fringe; heavy timber, high carbon density, flowers feed communities.' }),
  SP('tree','sal','Shorea robusta','শাল (Sal)','Sal','Dipterocarpaceae','native',
    [0.25,0.8,0.7,5.0,6.8,0.1,0,1.0,0.7,0.5],
    { apti:[14,12,16], dust:'M', r:7, h:25, dbh:55, wd:0.80, mat:45, roles:['canopy','forest','carbon'],
      note:'Dominant of Dooars and laterite forests; demands acidic, well-drained soil and fails on deltaic clay.' }),
  SP('tree','palash','Butea monosperma','পলাশ (Palash)','Flame of the forest','Fabaceae','native',
    [0.15,1.0,1.0,5.5,8.0,0.3,0,4.0,0.7,0.35],
    { apti:[13,12,15], dust:'M', r:6, h:12, dbh:35, wd:0.45, mat:20, nfix:true, roles:['understory','nfix','drought','cultural'],
      note:'Fixes nitrogen on the poorest laterite; tolerates saline and alkaline patches.' }),
  SP('tree','shimul','Bombax ceiba','শিমুল (Shimul)','Red silk cotton','Malvaceae','native',
    [0.5,0.9,0.7,5.5,8.0,0.4,0,2.0,0.5,0.35],
    { apti:[12,10,14], dust:'L', r:10, h:28, dbh:90, wd:0.33, mat:25, roles:['canopy','wildlife','fast'],
      note:'Emergent deciduous giant; soft wood, sensitive APTI, keep away from heavy traffic corridors.' }),
  SP('tree','bahera','Terminalia bellirica','বহেড়া (Bahera)','Beleric myrobalan','Combretaceae','native',
    [0.3,0.85,0.8,5.5,7.5,0.3,0,1.5,0.7,0.4],
    { apti:[14,12,16], dust:'M', r:9, h:25, dbh:65, wd:0.70, mat:35, roles:['canopy','medicinal','carbon'],
      note:'Tall buttressed forest tree of the laterite belt.' }),
  SP('tree','haritaki','Terminalia chebula','হরিতকী (Haritaki)','Chebulic myrobalan','Combretaceae','native',
    [0.2,0.9,0.9,5.5,7.5,0.2,0,1.5,0.8,0.45],
    { apti:[13,12,15], dust:'M', r:7, h:18, dbh:50, wd:0.80, mat:35, roles:['canopy','medicinal','slope'],
      note:'Drought-hardy on gravelly slopes.' }),
  SP('tree','amloki','Phyllanthus emblica','আমলকী (Amloki)','Indian gooseberry, Amla','Phyllanthaceae','native',
    [0.3,0.95,0.9,5.5,8.0,0.3,0,3.0,0.7,0.3],
    { apti:[14,12,16], dust:'M', r:5, h:10, dbh:30, wd:0.75, mat:15, roles:['understory','fruit','medicinal','drought'],
      note:'Light-crowned understory fruit tree for laterite and alluvium.' }),
  SP('tree','bel','Aegle marmelos','বেল (Bel)','Bael','Rutaceae','native',
    [0.4,1.0,0.9,5.5,8.5,0.4,0,4.0,0.6,0.3],
    { apti:[16,14,19], dust:'M', r:5, h:10, dbh:30, wd:0.80, mat:20, roles:['understory','fruit','cultural','drought'],
      note:'Thrives on alkaline and saline-fringe soils; tolerates brief flooding.' }),
  SP('tree','aam','Mangifera indica','আম (Aam)','Mango','Anacardiaceae','native',
    [0.35,0.9,0.7,5.5,7.8,0.35,0,2.0,0.5,0.25],
    { apti:[20,16,24], dust:'H', r:10, h:16, dbh:60, wd:0.55, mat:25, roles:['canopy','fruit','pollution','shade'],
      note:'Tolerant APTI class and broad shade crown; orchard soils must drain in the monsoon.' }),
  SP('tree','kanthal','Artocarpus heterophyllus','কাঁঠাল (Kanthal)','Jackfruit','Moraceae','native',
    [0.35,0.85,0.6,5.5,7.5,0.3,0,1.5,0.5,0.2],
    { apti:[17,14,20], dust:'H', r:8, h:15, dbh:50, wd:0.55, mat:20, roles:['canopy','fruit','shade'],
      note:'Household canopy of Bengal homesteads; sensitive to stagnant water.' }),
  SP('tree','tetul','Tamarindus indica','তেঁতুল (Tetul)','Tamarind','Fabaceae','naturalised',
    [0.3,1.0,1.0,5.5,8.5,0.3,0,4.0,0.6,0.3],
    { apti:[14,12,16], dust:'M', r:10, h:18, dbh:70, wd:0.85, mat:40, roles:['canopy','fruit','drought','carbon'],
      note:'Long-naturalised, extremely heat hardy, dense timber; slow.' }),
  SP('tree','sissoo','Dalbergia sissoo','শিশু (Shishu)','Sissoo, Indian rosewood','Fabaceae','native',
    [0.5,0.95,0.9,6.0,8.5,0.4,0,4.0,0.6,0.45],
    { apti:[15,12,18], dust:'M', r:7, h:20, dbh:50, wd:0.70, mat:25, nfix:true, roles:['canopy','nfix','riparian','timber'],
      note:'Riverine legume of the Terai and Gangetic plain; tolerates sandy floods, not stagnant clay.' }),
  SP('tree','gab','Diospyros malabarica','গাব (Gab)','Indian persimmon, Gaub','Ebenaceae','native',
    [0.85,0.8,0.5,5.5,7.8,0.85,0,2.0,0.4,0.25],
    { apti:[14,12,16], dust:'M', r:6, h:15, dbh:40, wd:0.75, mat:30, roles:['canopy','wetland','shade','riparian'],
      note:'Pond-margin evergreen of rural Bengal; dense shade, tolerates prolonged saturation.' }),
  SP('tree','jarul','Lagerstroemia speciosa','জারুল (Jarul)','Pride of India, Queen crape myrtle','Lythraceae','native',
    [0.75,0.85,0.5,5.5,7.8,0.7,0,2.0,0.4,0.25],
    { apti:[13,12,15], dust:'M', r:6, h:14, dbh:40, wd:0.60, mat:20, roles:['canopy','ornamental','wetland'],
      note:'Native swamp-edge flowering tree; ideal along retention basins.' }),
  SP('tree','ashok','Saraca asoca','অশোক (Ashok)','Ashoka','Fabaceae','native',
    [0.5,0.75,0.4,5.5,7.5,0.5,0,1.5,0.4,0.2],
    { apti:[16,14,19], dust:'M', r:5, h:9, dbh:28, wd:0.70, mat:20, roles:['understory','shade','cultural','ornamental'],
      note:'Shade-loving understory of moist evergreen margins; plant beneath canopy.' }),
  SP('tree','bakul','Mimusops elengi','বকুল (Bakul)','Spanish cherry, Bakul','Sapotaceae','native',
    [0.4,0.9,0.7,5.5,8.0,0.4,0,3.0,0.5,0.25],
    { apti:[17,15,20], dust:'H', r:7, h:14, dbh:45, wd:0.90, mat:30, roles:['canopy','pollution','cultural','shade'],
      note:'Dense evergreen, tolerant APTI class, very heavy wood; excellent avenue and courtyard tree.' }),
  SP('tree','champa','Magnolia champaca','চাঁপা (Champa)','Champak','Magnoliaceae','native',
    [0.3,0.7,0.5,5.5,7.0,0.3,0,1.0,0.6,0.4],
    { apti:[14,12,16], dust:'M', r:7, h:22, dbh:50, wd:0.55, mat:25, roles:['canopy','ornamental','cultural'],
      note:'Prefers deep, well-drained loam; suits the Terai and moist uplands.' }),
  SP('tree','sheora','Streblus asper','শেওড়া (Sheora)','Siamese rough bush, Sheora','Moraceae','native',
    [0.5,1.0,0.95,5.5,8.5,0.5,0,4.0,0.6,0.3],
    { apti:[15,13,17], dust:'H', r:4, h:7, dbh:22, wd:0.75, mat:15, roles:['understory','edge','pollution','hedge'],
      note:'Rough sandpaper leaves capture dust; indestructible small tree of village boundaries.' }),
  SP('tree','pitali','Trewia nudiflora','পিতালি (Pitali)','False white teak, Pitali','Euphorbiaceae','native',
    [0.95,0.8,0.3,5.5,7.8,0.9,0,2.0,0.3,0.25],
    { apti:[13,11,15], dust:'M', r:7, h:14, dbh:45, wd:0.40, mat:15, roles:['canopy','wetland','riparian','fast'],
      note:'Swamp forest tree of Bengal beels; fast, fruit for deer and birds.' }),
  SP('tree','barun','Crateva religiosa','বরুণ (Barun)','Sacred garlic pear, Barun','Capparaceae','native',
    [0.9,0.85,0.5,5.5,8.0,0.85,0,2.5,0.4,0.25],
    { apti:[13,11,15], dust:'M', r:6, h:12, dbh:38, wd:0.55, mat:20, roles:['canopy','riparian','wetland','ornamental'],
      note:'Riverbank tree of ghats and pond edges; showy flowers, tolerates saturation.' }),
  SP('tree','debdaru','Polyalthia longifolia','দেবদারু (Debdaru)','False ashoka','Annonaceae','native',
    [0.3,0.9,0.7,5.5,8.0,0.3,0,2.5,0.5,0.25],
    { apti:[20,17,26], dust:'H', r:3.5, h:15, dbh:35, wd:0.65, mat:15, roles:['edge','pollution','screen'],
      note:'Columnar evergreen screen with tolerant APTI class; standard CPCB greenbelt species.' }),
  SP('tree','putranjiva','Putranjiva roxburghii','পুত্রঞ্জীব (Putranjiva)','Child-life tree','Putranjivaceae','native',
    [0.3,0.9,0.8,5.5,8.0,0.3,0,2.5,0.5,0.3],
    { apti:[16,14,18], dust:'H', r:5, h:12, dbh:35, wd:0.70, mat:20, roles:['understory','pollution','screen','shade'],
      note:'Drooping evergreen, good particulate capture, tolerates heat and poor soils.' }),
  SP('tree','sonalu','Cassia fistula','সোনালু (Sonalu)','Golden shower, Amaltas','Fabaceae','native',
    [0.2,1.0,0.9,5.5,8.0,0.2,0,2.0,0.6,0.3],
    { apti:[13,11,16], dust:'M', r:5, h:10, dbh:30, wd:0.70, mat:15, roles:['understory','ornamental','drought'],
      note:'Needs free drainage; brilliant on laterite, poor on ponded clay.' }),
  SP('tree','chirol','Holoptelea integrifolia','চিরল (Chirol)','Indian elm','Ulmaceae','native',
    [0.3,1.0,0.9,6.0,8.5,0.3,0,3.0,0.6,0.35],
    { apti:[14,12,16], dust:'M', r:9, h:20, dbh:60, wd:0.60, mat:30, roles:['canopy','drought','shade'],
      note:'Broad shade tree for hot dry towns; tolerates alkaline soils.' }),
  SP('tree','sirish','Albizia lebbeck','শিরীষ (Sirish)','Siris, Woman\'s tongue','Fabaceae','native',
    [0.3,1.0,0.85,5.5,8.5,0.3,0,4.0,0.6,0.35],
    { apti:[15,13,18], dust:'M', r:9, h:16, dbh:50, wd:0.62, mat:15, nfix:true, roles:['canopy','nfix','drought','shade'],
      note:'Fast nitrogen-fixing shade for degraded laterite and saline fringes.' }),
  SP('tree','koroi','Albizia procera','কড়ই (Koroi)','White siris','Fabaceae','native',
    [0.6,0.95,0.7,5.5,8.0,0.5,0,3.0,0.5,0.3],
    { apti:[14,12,16], dust:'M', r:8, h:18, dbh:45, wd:0.62, mat:15, nfix:true, roles:['canopy','nfix','riparian'],
      note:'Tolerates seasonal flooding on alluvium; light crown suits mixed plantings.' }),
  SP('tree','mandar','Erythrina variegata','মান্দার (Mandar)','Indian coral tree','Fabaceae','native',
    [0.6,0.9,0.6,5.5,8.0,0.5,0,4.0,0.4,0.25],
    { apti:[13,11,15], dust:'L', r:6, h:14, dbh:40, wd:0.30, mat:12, nfix:true, roles:['canopy','nfix','coastal','fast'],
      note:'Coastal-tolerant legume, live fence of the delta; brittle in cyclonic wind.' }),
  SP('tree','gamar','Gmelina arborea','গামার (Gamar)','Gmelina, Gamhar','Lamiaceae','native',
    [0.4,0.85,0.7,5.0,7.5,0.3,0,1.5,0.6,0.5],
    { apti:[13,11,15], dust:'M', r:7, h:18, dbh:45, wd:0.45, mat:12, roles:['canopy','fast','timber'],
      note:'Fast Terai timber; needs deep, drained soil.' }),
  SP('tree','paras','Thespesia populnea','পারস পিপুল (Paras pipul)','Portia tree','Malvaceae','native',
    [0.8,0.9,0.7,6.0,8.5,0.7,0,10,0.5,0.15],
    { apti:[16,14,18], dust:'M', r:6, h:12, dbh:35, wd:0.60, mat:15, roles:['canopy','coastal','shelterbelt'],
      note:'Littoral evergreen for saline coasts and creek banks.' }),
  SP('tree','dhaura','Anogeissus latifolia','ধাউরা (Dhaura)','Axlewood','Combretaceae','native',
    [0.1,1.0,1.0,5.5,7.8,0.1,0,1.5,0.9,0.4],
    { apti:[13,11,15], dust:'M', r:6, h:16, dbh:45, wd:0.87, mat:35, roles:['canopy','drought','slope','carbon'],
      note:'Very dense timber of dry rocky slopes; highest drought rating.' }),
  SP('tree','piyal','Buchanania lanzan','পিয়াল (Piyal)','Chironji','Anacardiaceae','native',
    [0.1,1.0,1.0,5.0,7.5,0.1,0,1.0,0.8,0.4],
    { apti:[12,11,14], dust:'M', r:5, h:10, dbh:30, wd:0.60, mat:20, roles:['understory','drought','livelihood'],
      note:'Companion of Sal and Mahua on laterite; edible kernels.' }),
  SP('tree','kusum','Schleichera oleosa','কুসুম (Kusum)','Ceylon oak, Kusum','Sapindaceae','native',
    [0.2,1.0,0.9,5.5,7.8,0.2,0,1.5,0.7,0.4],
    { apti:[14,12,16], dust:'M', r:8, h:18, dbh:60, wd:0.95, mat:35, roles:['canopy','drought','carbon','shade'],
      note:'Densest wood in the database; slow, long-lived shade for the Rarh.' }),
  SP('tree','hollock','Terminalia myriocarpa','পানিসাজ (Panisaj)','Hollock, East Indian almond','Combretaceae','native',
    [0.7,0.4,0.5,5.0,7.0,0.6,0,1.0,0.7,0.5],
    { apti:null, dust:'M', r:9, h:30, dbh:70, wd:0.60, mat:30, roles:['canopy','riparian','forest','carbon'],
      note:'Riverside giant of the Dooars and lower hills; not a plains species.' }),
  SP('tree','lampati','Duabanga grandiflora','লামপাতি (Lampati)','Duabanga','Lythraceae','native',
    [0.7,0.4,0.4,5.0,7.0,0.6,0,1.0,0.7,0.5],
    { apti:null, dust:'M', r:8, h:28, dbh:60, wd:0.40, mat:20, roles:['canopy','riparian','fast'],
      note:'Fast pioneer along Terai streams.' }),
  SP('tree','kainjal','Bischofia javanica','কাঞ্জল (Kainjal)','Bishop wood','Phyllanthaceae','native',
    [0.6,0.6,0.5,5.0,7.5,0.6,0,1.5,0.6,0.5],
    { apti:[14,12,16], dust:'M', r:8, h:22, dbh:60, wd:0.65, mat:25, roles:['canopy','riparian','shade'],
      note:'Moist-site evergreen of the Terai and north Bengal plains.' }),
  SP('tree','utis','Alnus nepalensis','উতিস (Utis)','Nepal alder','Betulaceae','native',
    [0.5,0.1,0.4,4.5,6.5,0.5,0,0.5,1.0,1.0],
    { apti:[14,12,16], dust:'M', r:6, h:22, dbh:50, wd:0.37, mat:15, nfix:true, roles:['canopy','slope','nfix','landslide','fast'],
      note:'The landslide-repair tree of the Darjeeling hills; actinorhizal nitrogen fixer, colonises raw scars.' }),
  SP('tree','chilauni','Schima wallichii','চিলাউনি (Chilauni)','Needlewood, Chilauni','Theaceae','native',
    [0.3,0.3,0.6,4.5,6.5,0.3,0,0.5,0.9,0.8],
    { apti:null, dust:'M', r:7, h:22, dbh:55, wd:0.62, mat:30, roles:['canopy','slope','forest'],
      note:'Mid-hill evergreen from 600 to 2000 m; tolerates poor acidic soils on slopes.' }),
  SP('tree','buk','Quercus lamellosa','বুক (Buk)','Himalayan oak','Fagaceae','native',
    [0.2,0.05,0.5,4.5,6.5,0.2,0,0.5,0.9,1.0],
    { apti:null, dust:'M', r:9, h:28, dbh:75, wd:0.75, mat:60, roles:['canopy','forest','carbon','watershed'],
      note:'Climax oak of the upper hills above 1800 m; slow, immense carbon and water-holding value.' }),
  SP('tree','gurans','Rhododendron arboreum','গুরাঁস (Gurans)','Tree rhododendron','Ericaceae','native',
    [0.2,0.0,0.5,4.5,6.0,0.2,0,0.3,1.0,1.0],
    { apti:null, dust:'L', r:4, h:9, dbh:28, wd:0.60, mat:30, roles:['understory','slope','ornamental','cultural'],
      note:'Ridge species above 1500 m on acidic humus; frost hardy, heat intolerant.' }),
  SP('tree','ghogechanp','Magnolia campbellii','ঘোগে চাঁপ (Ghoge chanp)','Campbell\'s magnolia','Magnoliaceae','native',
    [0.3,0.0,0.4,4.5,6.5,0.3,0,0.3,0.8,1.0],
    { apti:null, dust:'L', r:7, h:22, dbh:60, wd:0.50, mat:35, roles:['canopy','ornamental','forest'],
      note:'Spring-flowering giant of the Singalila and Darjeeling forests.' }),
  SP('tree','paiyun','Prunus cerasoides','পাইয়ুঁ (Paiyun)','Himalayan wild cherry','Rosaceae','native',
    [0.2,0.2,0.7,5.0,7.0,0.2,0,0.5,0.9,0.9],
    { apti:null, dust:'M', r:5, h:12, dbh:32, wd:0.60, mat:20, roles:['understory','slope','ornamental','fast'],
      note:'Autumn-flowering pioneer of hill roadsides and terraces.' }),
  SP('tree','katus','Castanopsis indica','কাটুস (Katus)','Indian chestnut','Fagaceae','native',
    [0.2,0.15,0.5,4.5,6.5,0.2,0,0.5,0.9,0.85],
    { apti:null, dust:'M', r:8, h:22, dbh:60, wd:0.65, mat:40, roles:['canopy','forest','carbon'],
      note:'Mid-hill chestnut with Schima; wildlife mast.' }),
  SP('tree','saur','Betula alnoides','সাউর (Saur)','Indian birch','Betulaceae','native',
    [0.3,0.15,0.5,4.5,6.5,0.3,0,0.5,0.9,0.9],
    { apti:null, dust:'M', r:6, h:22, dbh:50, wd:0.60, mat:25, roles:['canopy','slope','forest'],
      note:'Pioneer birch of landslide scars and stream banks in the hills.' }),
  /* mangroves, tidal gate */
  SP('tree','sundari','Heritiera fomes','সুন্দরী (Sundari)','Sundri','Malvaceae','native',
    [1.0,0.6,0.2,6.5,8.5,1.0,2,20,0.1,0.1],
    { apti:null, dust:null, r:5, h:14, dbh:35, wd:0.85, mat:30, hab:'tidal', roles:['canopy','mangrove','carbon','coastal'],
      note:'Namesake of the Sundarbans; prefers the fresher upstream tidal zone, sensitive to rising salinity.' }),
  SP('tree','keora','Sonneratia apetala','কেওড়া (Keora)','Mangrove apple','Lythraceae','native',
    [1.0,0.65,0.15,6.5,8.8,1.0,2,30,0.1,0.1],
    { apti:null, dust:null, r:5, h:14, dbh:35, wd:0.55, mat:15, hab:'tidal', roles:['canopy','mangrove','pioneer','coastal'],
      note:'Fast pioneer on new mudflats; first choice for accreting char land.' }),
  SP('tree','bain','Avicennia officinalis','বাইন (Bain)','Indian mangrove','Acanthaceae','native',
    [1.0,0.7,0.2,6.5,8.8,1.0,3,40,0.1,0.1],
    { apti:null, dust:null, r:5, h:11, dbh:32, wd:0.65, mat:20, hab:'tidal', roles:['canopy','mangrove','coastal','embankment'],
      note:'Most salt-tolerant tree here; pencil roots trap sediment along embankments.' }),
  SP('tree','genwa','Excoecaria agallocha','গেঁওয়া (Genwa)','Blinding tree, Milky mangrove','Euphorbiaceae','native',
    [1.0,0.7,0.2,6.5,8.5,1.0,2,30,0.1,0.1],
    { apti:null, dust:null, r:4, h:9, dbh:25, wd:0.45, mat:15, hab:'tidal', roles:['understory','mangrove','coastal'],
      note:'Landward mangrove of higher ground; caustic latex, keep from paths.' }),
  SP('tree','kankra','Bruguiera gymnorhiza','কাঁকড়া (Kankra)','Large-leafed orange mangrove','Rhizophoraceae','native',
    [1.0,0.65,0.15,6.5,8.5,1.0,3,35,0.1,0.1],
    { apti:null, dust:null, r:4, h:12, dbh:30, wd:0.85, mat:25, hab:'tidal', roles:['canopy','mangrove','carbon'],
      note:'Knee-rooted mangrove of the mid-intertidal zone.' }),
  /* naturalised coastal standard */
  SP('tree','jhau','Casuarina equisetifolia','ঝাউ (Jhau)','Casuarina, Beach sheoak','Casuarinaceae','naturalised',
    [0.4,1.0,0.95,5.5,8.5,0.3,0,8,0.7,0.2],
    { apti:[15,12,17], dust:'M', r:4, h:18, dbh:30, wd:0.83, mat:12, nfix:true, roles:['shelterbelt','coastal','nfix','fast'],
      note:'Naturalised coastal shelterbelt standard on dune sand; not for clay or freshwater wetlands.' }),
  /* exotics kept for screening */
  SP('tree','krishnachura','Delonix regia','কৃষ্ণচূড়া (Krishnachura)','Gulmohar, Flame tree','Fabaceae','exotic',
    [0.3,0.95,0.8,6.0,7.5,0.2,0,2.0,0.3,0.2],
    { apti:[12,10,16], dust:'L', r:9, h:14, dbh:55, wd:0.45, mat:20, roles:['ornamental'],
      note:'Named in the framework as maladapted: shallow plate roots uproot in waterlogged clay under cyclonic shear.' }),
  SP('tree','radhachura','Peltophorum pterocarpum','রাধাচূড়া (Radhachura)','Copperpod, Yellow flame','Fabaceae','exotic',
    [0.3,0.95,0.8,6.0,8.0,0.2,0,3.0,0.3,0.2],
    { apti:[13,11,15], dust:'L', r:8, h:16, dbh:50, wd:0.62, mat:20, roles:['ornamental'],
      note:'Named in the framework as maladapted; frequent windthrow on saturated soils.' }),
  SP('tree','conocarpus','Conocarpus erectus','কনোকার্পাস (Conocarpus)','Buttonwood','Combretaceae','exotic',
    [0.6,1.0,1.0,6.0,8.5,0.6,0,15,0.5,0.1],
    { apti:[18,16,21], dust:'H', r:4, h:12, dbh:30, wd:0.75, mat:10, roles:['screen'],
      note:'Screened out regardless of score: extreme transpiration depletes water tables, allergenic pollen, no native fauna value.' }),
  SP('tree','eucalyptus','Eucalyptus tereticornis','ইউক্যালিপটাস (Eucalyptus)','Forest red gum','Myrtaceae','exotic',
    [0.3,1.0,0.9,5.0,8.0,0.3,0,4,0.6,0.4],
    { apti:[14,12,17], dust:'L', r:4, h:30, dbh:40, wd:0.80, mat:12, roles:['timber'],
      note:'Screened out: high water draw, allelopathic litter, minimal understory.' }),
  SP('tree','akashmoni','Acacia auriculiformis','আকাশমণি (Akashmoni)','Earleaf acacia','Fabaceae','exotic',
    [0.3,1.0,1.0,4.5,8.0,0.3,0,5,0.7,0.2],
    { apti:[16,14,18], dust:'M', r:5, h:16, dbh:35, wd:0.65, mat:10, nfix:true, roles:['plantation'],
      note:'Screened out: monoculture plantation species displacing Sal understory on laterite.' }),
  SP('tree','subabul','Leucaena leucocephala','সুবাবুল (Subabul)','Leucaena, Subabul','Fabaceae','exotic',
    [0.2,1.0,1.0,6.0,8.5,0.2,0,4,0.6,0.15],
    { apti:[15,13,17], dust:'M', r:4, h:10, dbh:20, wd:0.65, mat:6, nfix:true, roles:['fodder'],
      note:'Screened out: listed invasive, seeds prolifically into wasteland.' }),
  SP('tree','dhupi','Cryptomeria japonica','ধুপি (Dhupi)','Japanese cedar','Cupressaceae','exotic',
    [0.2,0.0,0.4,4.5,6.5,0.2,0,0.3,0.9,1.0],
    { apti:null, dust:'M', r:4, h:30, dbh:50, wd:0.35, mat:30, roles:['plantation'],
      note:'Screened out: colonial hill monoculture with acidic litter and no undergrowth.' }),

  /* =========================== SHRUBS =========================== */
  SP('shrub','shiuli','Nyctanthes arbor-tristis','শিউলি (Shiuli)','Night-flowering jasmine','Oleaceae','native',
    [0.4,0.85,0.7,5.5,8.0,0.4,0,2.0,0.5,0.35],
    { apti:[15,13,17], dust:'M', r:2.0, h:5, bio:25, roles:['understory','cultural','ornamental'],
      note:'Autumn-flowering shrub of every Bengal courtyard; tolerates partial shade.' }),
  SP('shrub','kamini','Murraya paniculata','কামিনী (Kamini)','Orange jasmine','Rutaceae','native',
    [0.3,0.85,0.7,5.5,8.0,0.3,0,2.0,0.5,0.3],
    { apti:[14,12,16], dust:'H', r:1.8, h:4, bio:18, roles:['hedge','pollution','ornamental'],
      note:'Dense glossy hedge, good particulate capture; needs drainage.' }),
  SP('shrub','rangan','Ixora coccinea','রঙ্গন (Rangan)','Jungle geranium','Rubiaceae','native',
    [0.4,0.75,0.5,5.0,7.0,0.4,0,1.5,0.4,0.2],
    { apti:[15,13,17], dust:'M', r:1.2, h:2.5, bio:8, roles:['understory','ornamental'],
      note:'Prefers acidic, moist loam under light shade.' }),
  SP('shrub','joba','Hibiscus rosa-sinensis','জবা (Joba)','China rose, Shoe flower','Malvaceae','naturalised',
    [0.4,0.85,0.6,5.5,7.8,0.4,0,2.5,0.4,0.2],
    { apti:[16,14,18], dust:'H', r:1.5, h:3, bio:12, roles:['hedge','pollution','cultural'],
      note:'Long-naturalised temple shrub; frequent CPCB greenbelt recommendation.' }),
  SP('shrub','akanda','Calotropis gigantea','আকন্দ (Akanda)','Crown flower','Apocynaceae','native',
    [0.2,1.0,1.0,6.0,8.5,0.2,0,6,0.6,0.3],
    { apti:[24,20,28], dust:'H', r:1.5, h:3, bio:10, roles:['pollution','drought','wasteland'],
      note:'Highest shrub APTI recorded in Indian studies; colonises the harshest fills, saline fringes and coal-belt spoil.' }),
  SP('shrub','bhant','Clerodendrum infortunatum','ভাঁট (Bhant)','Hill glory bower','Lamiaceae','native',
    [0.5,0.8,0.5,5.0,7.5,0.55,0,1.5,0.5,0.35],
    { apti:[14,12,16], dust:'M', r:1.2, h:2, bio:6, roles:['understory','wildlife','fast'],
      note:'Self-seeding understory of moist edges; pollinator resource.' }),
  SP('shrub','bonjui','Clerodendrum inerme','বনজুঁই (Bon jui)','Seaside clerodendrum','Lamiaceae','native',
    [0.8,0.9,0.6,6.0,8.5,0.8,0,12,0.5,0.15],
    { apti:[15,13,17], dust:'M', r:1.5, h:2, bio:8, roles:['coastal','hedge','embankment'],
      note:'Salt-spray hedge of the coast and tidal banks; clipped hedge standard in Kolkata.' }),
  SP('shrub','nishinda','Vitex negundo','নিশিন্দা (Nishinda)','Five-leaved chaste tree','Lamiaceae','native',
    [0.7,0.9,0.8,5.5,8.5,0.65,0,4,0.7,0.4],
    { apti:[14,12,16], dust:'M', r:2.0, h:4, bio:20, roles:['riparian','hedge','medicinal','edge'],
      note:'Riverbank stabiliser that tolerates both flooding and drought.' }),
  SP('shrub','basak','Justicia adhatoda','বাসক (Basak)','Malabar nut','Acanthaceae','native',
    [0.3,0.85,0.7,5.5,8.0,0.3,0,2,0.6,0.35],
    { apti:[16,14,18], dust:'H', r:1.5, h:2.5, bio:8, roles:['medicinal','hedge','pollution'],
      note:'Large soft leaves trap dust; classic medicinal hedge.' }),
  SP('shrub','mehendi','Lawsonia inermis','মেহেদি (Mehendi)','Henna','Lythraceae','native',
    [0.3,1.0,0.9,6.0,8.5,0.4,0,5,0.6,0.3],
    { apti:[14,12,16], dust:'M', r:1.5, h:3, bio:10, roles:['hedge','drought','livelihood'],
      note:'Alkaline and saline tolerant hedge for hot dry sites.' }),
  SP('shrub','dhataki','Woodfordia fruticosa','ধাতকী (Dhataki)','Fire-flame bush','Lythraceae','native',
    [0.1,0.95,1.0,5.0,7.0,0.1,0,1,0.8,0.5],
    { apti:[13,11,15], dust:'M', r:1.5, h:2.5, bio:8, roles:['slope','drought','pollinator'],
      note:'Rocky laterite slopes and hill scarps; excellent erosion check.' }),
  SP('shrub','shiakul','Ziziphus oenoplia','শিয়াকুল (Shiakul)','Jackal jujube','Rhamnaceae','native',
    [0.2,1.0,1.0,5.5,8.5,0.2,0,3,0.7,0.4],
    { apti:[13,11,15], dust:'M', r:1.5, h:3, bio:10, roles:['hedge','drought','wildlife','thorny'],
      note:'Thorny thicket for the driest laterite; bird refuge.' }),
  SP('shrub','karamcha','Carissa carandas','করমচা (Karamcha)','Karonda','Apocynaceae','native',
    [0.2,0.95,0.9,5.5,8.0,0.2,0,3,0.6,0.35],
    { apti:[15,13,17], dust:'M', r:1.8, h:3, bio:14, roles:['hedge','fruit','drought','thorny'],
      note:'Impenetrable fruiting hedge; dislikes wet feet.' }),
  SP('shrub','baichi','Flacourtia indica','বৈঁচি (Baichi)','Governor\'s plum','Salicaceae','native',
    [0.3,0.9,0.9,5.5,8.0,0.3,0,2,0.7,0.4],
    { apti:[13,11,15], dust:'M', r:2.0, h:4, bio:18, roles:['hedge','fruit','drought','wildlife'],
      note:'Laterite and forest-edge fruiting shrub.' }),
  SP('shrub','belphul','Jasminum sambac','বেলফুল (Bel phul)','Arabian jasmine','Oleaceae','naturalised',
    [0.3,0.8,0.6,5.5,7.8,0.3,0,1.5,0.4,0.25],
    { apti:[14,12,16], dust:'M', r:1.2, h:1.5, bio:5, roles:['ornamental','cultural','livelihood'],
      note:'Garland flower economy of Bengal; drained loam.' }),
  SP('shrub','tagar','Tabernaemontana divaricata','টগর (Tagar)','Crape jasmine','Apocynaceae','native',
    [0.4,0.8,0.6,5.5,7.8,0.4,0,1.5,0.4,0.25],
    { apti:[15,13,17], dust:'H', r:1.2, h:2, bio:6, roles:['understory','pollution','ornamental'],
      note:'CPCB-listed dust capturer; tolerates shade and clay if not ponded.' }),
  SP('shrub','gandharaj','Gardenia jasminoides','গন্ধরাজ (Gandharaj)','Cape jasmine','Rubiaceae','naturalised',
    [0.4,0.75,0.5,5.0,6.8,0.4,0,1,0.4,0.3],
    { apti:[14,12,16], dust:'M', r:1.2, h:2, bio:6, roles:['ornamental','understory'],
      note:'Needs acidic soil; chlorotic on alkaline alluvium.' }),
  SP('shrub','kantajati','Barleria prionitis','কাঁটাজাতি (Kanta jati)','Porcupine flower','Acanthaceae','native',
    [0.2,1.0,0.9,5.5,8.5,0.2,0,3,0.7,0.35],
    { apti:[14,12,16], dust:'M', r:0.8, h:1.2, bio:2, roles:['drought','hedge','medicinal'],
      note:'Low spiny hedge for the hottest, driest edges.' }),
  SP('shrub','chita','Plumbago zeylanica','চিতা (Chita)','Ceylon leadwort','Plumbaginaceae','native',
    [0.3,0.9,0.8,5.5,8.0,0.3,0,2,0.6,0.35],
    { apti:[13,11,15], dust:'L', r:0.8, h:1, bio:1.5, roles:['understory','medicinal','drought'],
      note:'Sprawling understory herb-shrub of forest margins.' }),
  SP('shrub','keya','Pandanus odorifer','কেয়া (Keya)','Fragrant screwpine','Pandanaceae','native',
    [0.9,0.9,0.7,6.0,8.5,0.8,0,10,0.6,0.15],
    { apti:null, dust:'L', r:2.5, h:4, bio:40, roles:['coastal','dune','embankment','cultural'],
      note:'Prop-rooted dune and creek-bank binder of the delta coast.' }),
  SP('shrub','goran','Ceriops decandra','গরান (Goran)','Goran mangrove','Rhizophoraceae','native',
    [1.0,0.7,0.2,6.5,8.5,1.0,3,35,0.1,0.1],
    { apti:null, dust:null, r:1.5, h:4, bio:30, hab:'tidal', roles:['mangrove','coastal','understory'],
      note:'Shrubby mangrove of the high intertidal; dense stands on Sundarbans embankments.' }),
  SP('shrub','khalsi','Aegiceras corniculatum','খলসী (Khalsi)','River mangrove','Primulaceae','native',
    [1.0,0.7,0.2,6.5,8.5,1.0,2,30,0.1,0.1],
    { apti:null, dust:null, r:1.5, h:3, bio:20, hab:'tidal', roles:['mangrove','coastal','honey'],
      note:'Creek-bank mangrove shrub, key honey plant of the Sundarbans.' }),
  SP('shrub','hargoza','Acanthus ilicifolius','হারগোজা (Hargoza)','Holly mangrove','Acanthaceae','native',
    [1.0,0.8,0.2,6.0,8.5,1.0,1.5,25,0.2,0.15],
    { apti:null, dust:null, r:1.0, h:1.5, bio:4, hab:'brackish', roles:['brackish','embankment','medicinal'],
      note:'Brackish creek edges and embankment toes; tolerates fresh floods, needs some salinity.' }),
  SP('shrub','jayanti','Sesbania sesban','জয়ন্তী (Jayanti)','Egyptian riverhemp','Fabaceae','native',
    [0.8,0.9,0.5,5.5,8.5,0.8,0,5,0.3,0.2],
    { apti:[14,12,16], dust:'M', r:1.5, h:4, bio:15, nfix:true, roles:['nfix','wetland','fast','fodder'],
      note:'Fast nitrogen-fixing nurse shrub for waterlogged, saline-fringe soils.' }),
  SP('shrub','phutki','Melastoma malabathricum','ফুটকি (Phutki)','Malabar melastome','Melastomataceae','native',
    [0.6,0.35,0.5,4.5,6.5,0.6,0,0.5,0.8,0.5],
    { apti:[13,11,15], dust:'M', r:1.2, h:2, bio:6, roles:['slope','understory','acid','pollinator'],
      note:'Acid-soil shrub of Terai and lower hill clearings.' }),
  SP('shrub','argeli','Daphne bholua','আরগেলি (Argeli)','Nepalese paper plant','Thymelaeaceae','native',
    [0.2,0.0,0.6,4.5,6.5,0.2,0,0.3,0.9,1.0],
    { apti:null, dust:'L', r:1.2, h:2.5, bio:6, roles:['understory','slope','livelihood'],
      note:'Upper hill understory; bark for handmade paper.' }),
  SP('shrub','chutro','Berberis aristata','চুত্রো (Chutro)','Indian barberry','Berberidaceae','native',
    [0.1,0.05,0.8,5.0,7.0,0.1,0,0.5,1.0,1.0],
    { apti:null, dust:'L', r:1.2, h:2.5, bio:6, roles:['slope','hedge','medicinal','thorny'],
      note:'Spiny hill hedge on dry sunny slopes.' }),
  SP('shrub','mahonia','Mahonia napaulensis','জমানেমান্ড্রো (Jamanemandro)','Nepal mahonia','Berberidaceae','native',
    [0.2,0.05,0.6,4.5,6.5,0.2,0,0.3,0.9,1.0],
    { apti:null, dust:'L', r:1.5, h:3, bio:8, roles:['understory','slope','ornamental'],
      note:'Evergreen hill understory with winter flowers.' }),
  SP('shrub','aiselu','Rubus ellipticus','ঐসেলু (Aiselu)','Yellow Himalayan raspberry','Rosaceae','native',
    [0.3,0.1,0.7,4.5,6.5,0.3,0,0.5,1.0,1.0],
    { apti:null, dust:'L', r:1.5, h:2, bio:6, roles:['slope','fruit','wildlife'],
      note:'Rapid slope cover after disturbance; can be aggressive, manage by cutting.' }),
  SP('shrub','asare','Viburnum erubescens','আসারে (Asare)','Reddish viburnum','Viburnaceae','native',
    [0.3,0.05,0.5,4.5,6.5,0.3,0,0.3,0.9,1.0],
    { apti:null, dust:'L', r:1.5, h:3, bio:8, roles:['understory','ornamental','wildlife'],
      note:'Fragrant hill understory shrub.' }),
  SP('shrub','kurchi','Holarrhena pubescens','কুর্চি (Kurchi)','Kurchi, Tellicherry bark','Apocynaceae','native',
    [0.2,0.95,0.9,5.5,7.8,0.2,0,1.5,0.7,0.4],
    { apti:[14,12,16], dust:'M', r:2.5, h:6, bio:35, roles:['understory','drought','medicinal','edge'],
      note:'Tall shrub of laterite Sal country; white summer flowers.' }),
  SP('shrub','antamora','Helicteres isora','আঁতমোড়া (Antamora)','Indian screw tree','Malvaceae','native',
    [0.2,0.95,0.9,5.5,7.8,0.2,0,1.5,0.7,0.4],
    { apti:[13,11,15], dust:'M', r:1.5, h:3, bio:8, roles:['understory','drought','slope'],
      note:'Dry deciduous understory on gravelly slopes.' }),
  SP('shrub','ulatkambal','Abroma augusta','উলটকম্বল (Ulatkambal)','Devil\'s cotton','Malvaceae','native',
    [0.5,0.8,0.4,5.5,7.5,0.5,0,1.5,0.4,0.3],
    { apti:[13,11,15], dust:'M', r:1.5, h:3, bio:8, roles:['understory','medicinal','shade'],
      note:'Large-leaved shade shrub of moist homestead groves.' }),
  SP('shrub','ashsheora','Glycosmis pentaphylla','আশশেওড়া (Ash sheora)','Orangeberry','Rutaceae','native',
    [0.5,0.85,0.7,5.5,8.0,0.5,0,2,0.5,0.3],
    { apti:[15,13,17], dust:'M', r:1.5, h:3, bio:10, roles:['understory','wildlife','hedge','shade'],
      note:'The default understory shrub of Bengal groves; shade tolerant, self-sustaining.' }),
  SP('shrub','panjuli','Phyllanthus reticulatus','পানজুলি (Panjuli)','Black-honey shrub','Phyllanthaceae','native',
    [0.7,0.9,0.7,5.5,8.0,0.7,0,3,0.5,0.3],
    { apti:[14,12,16], dust:'M', r:2.0, h:4, bio:15, roles:['riparian','hedge','wildlife'],
      note:'Pond-margin and canal-bank shrub, fruit for birds.' }),
  /* exotics kept for screening */
  SP('shrub','bougainvillea','Bougainvillea spectabilis','বাগানবিলাস (Baganbilas)','Bougainvillea','Nyctaginaceae','exotic',
    [0.2,1.0,1.0,5.5,8.5,0.2,0,4,0.6,0.25],
    { apti:[19,17,22], dust:'H', r:2.0, h:4, bio:15, roles:['ornamental'],
      note:'Screened out as exotic; tolerant APTI but no native pollinator or fauna value.' }),
  SP('shrub','karabi','Nerium oleander','করবী (Karabi)','Oleander','Apocynaceae','exotic',
    [0.3,1.0,1.0,6.0,8.5,0.3,0,6,0.6,0.4],
    { apti:[22,18,27], dust:'H', r:1.5, h:3, bio:10, roles:['ornamental'],
      note:'Screened out: exotic and acutely toxic in public space despite high APTI.' }),
  SP('shrub','lantana','Lantana camara','পুটুস (Putus)','Lantana','Verbenaceae','exotic',
    [0.3,1.0,1.0,5.0,8.5,0.3,0,3,0.8,0.4],
    { apti:[17,15,19], dust:'M', r:1.5, h:2, bio:6, roles:['invasive'],
      note:'Screened out: one of India\'s worst invasives.' }),
  SP('shrub','beharikalmi','Ipomoea carnea','বেহারি কলমি (Behari kalmi)','Bush morning glory','Convolvulaceae','exotic',
    [1.0,1.0,0.8,5.5,8.5,1.0,0,4,0.3,0.3],
    { apti:[18,16,20], dust:'M', r:1.5, h:3, bio:8, roles:['invasive'],
      note:'Screened out: invasive wetland weed choking canals and beels.' }),

  /* =========================== GROUND COVERS =========================== */
  SP('ground','durba','Cynodon dactylon','দূর্বা (Durba)','Bermuda grass, Doob','Poaceae','native',
    [0.6,1.0,0.9,5.5,8.5,0.5,0,6,0.6,0.7],
    { apti:[13,11,15], dust:'M', bio:0.6, roles:['turf','pollution','cultural','drought'],
      note:'Sacred lawn grass of Bengal; heat and salt tolerant, recovers after floods, needs full sun.' }),
  SP('ground','carpetgrass','Axonopus compressus','কার্পেট ঘাস (Carpet ghas)','Carpet grass','Poaceae','naturalised',
    [0.6,0.7,0.4,5.0,7.5,0.6,0,1,0.5,0.3],
    { apti:[12,10,14], dust:'M', bio:0.5, roles:['turf','shade'],
      note:'Shade-tolerant lawn under tree canopy in humid Bengal.' }),
  SP('ground','manila','Zoysia matrella','মানিলা ঘাস (Manila ghas)','Manila grass','Poaceae','native',
    [0.4,0.9,0.8,5.5,8.0,0.3,0,10,0.6,0.5],
    { apti:[12,10,14], dust:'M', bio:0.6, roles:['turf','coastal','drought'],
      note:'Coastal-origin fine turf; salt spray tolerant, dislikes ponding.' }),
  SP('ground','vetiver','Chrysopogon zizanioides','খসখস (Khas khas)','Vetiver','Poaceae','native',
    [0.95,1.0,1.0,4.5,9.0,0.9,0,8,1.0,0.6],
    { apti:[14,12,16], dust:'M', bio:3.0, roles:['slope','embankment','wetland','drought','engineering'],
      note:'Three-metre root curtain; the one grass that holds mounds, bunds and flood lines alike.' }),
  SP('ground','thankuni','Centella asiatica','থানকুনি (Thankuni)','Asiatic pennywort','Apiaceae','native',
    [0.8,0.7,0.3,5.0,7.5,0.85,0,1.5,0.4,0.5],
    { apti:[14,12,16], dust:'L', bio:0.3, roles:['wetland','shade','medicinal','edible'],
      note:'Creeping cover for damp shaded ground and basin margins.' }),
  SP('ground','brahmi','Bacopa monnieri','ব্রাহ্মী (Brahmi)','Water hyssop','Plantaginaceae','native',
    [1.0,0.8,0.1,5.5,8.5,1.0,0,6,0.3,0.4],
    { apti:null, dust:'L', bio:0.3, roles:['wetland','medicinal','basin'],
      note:'Mat-forming cover for the wet floor of retention basins; tolerates brackish water.' }),
  SP('ground','kalmi','Ipomoea aquatica','কলমি (Kalmi)','Water spinach','Convolvulaceae','native',
    [1.0,0.9,0.1,5.5,8.0,1.0,0,2,0.2,0.3],
    { apti:null, dust:'L', bio:0.6, roles:['wetland','edible','basin'],
      note:'Floating and creeping wetland cover; productive in monsoon basins.' }),
  SP('ground','sushni','Marsilea minuta','সুষনি (Sushni)','Dwarf water clover','Marsileaceae','native',
    [1.0,0.8,0.15,5.5,7.5,1.0,0,1,0.2,0.4],
    { apti:null, dust:'L', bio:0.2, roles:['wetland','edible','basin'],
      note:'Aquatic fern for seasonally flooded floors.' }),
  SP('ground','kulekhara','Hygrophila auriculata','কুলেখাড়া (Kulekhara)','Marsh barbel','Acanthaceae','native',
    [1.0,0.9,0.2,5.5,8.0,1.0,0,3,0.3,0.4],
    { apti:null, dust:'L', bio:0.5, roles:['wetland','medicinal','basin'],
      note:'Spiny marsh herb of ditch edges; iron-rich leaf economy.' }),
  SP('ground','sanchi','Alternanthera sessilis','সাঁচি শাক (Sanchi shak)','Sessile joyweed','Amaranthaceae','native',
    [0.9,0.9,0.4,5.5,8.0,0.9,0,2,0.4,0.4],
    { apti:[15,13,17], dust:'M', bio:0.4, roles:['wetland','edible','basin'],
      note:'Rapid creeping cover for wet margins and drain edges.' }),
  SP('ground','kesut','Eclipta prostrata','কেশুত (Kesut)','False daisy','Asteraceae','native',
    [0.9,0.9,0.3,5.5,8.0,0.9,0,2,0.3,0.4],
    { apti:null, dust:'L', bio:0.3, roles:['wetland','medicinal'],
      note:'Damp-ground annual, self-sowing along basins.' }),
  SP('ground','bhuiokra','Phyla nodiflora','ভুঁই ওকরা (Bhui okra)','Frog fruit','Verbenaceae','native',
    [0.8,1.0,0.8,5.5,8.5,0.7,0,8,0.6,0.5],
    { apti:[14,12,16], dust:'M', bio:0.4, roles:['turf','pollution','coastal','pollinator','drought'],
      note:'The best native lawn substitute: mows, takes footfall, floods, salt and heat.' }),
  SP('ground','kudaliya','Desmodium triflorum','কুদালিয়া (Kudaliya)','Three-flower beggarweed','Fabaceae','native',
    [0.5,0.9,0.8,5.0,8.0,0.4,0,2,0.6,0.5],
    { apti:[13,11,15], dust:'L', bio:0.3, nfix:true, roles:['turf','nfix','pollinator'],
      note:'Nitrogen-fixing creeping legume in lawns and orchard floors.' }),
  SP('ground','shankhapushpi','Evolvulus alsinoides','শঙ্খপুষ্পী (Shankhapushpi)','Dwarf morning glory','Convolvulaceae','native',
    [0.1,1.0,1.0,5.5,8.0,0.1,0,2,0.7,0.5],
    { apti:null, dust:'L', bio:0.15, roles:['drought','medicinal','laterite'],
      note:'Prostrate cover for gravelly laterite in full sun.' }),
  SP('ground','amrul','Oxalis corniculata','আমরুল (Amrul)','Creeping woodsorrel','Oxalidaceae','native',
    [0.5,0.7,0.5,5.0,7.5,0.4,0,1,0.6,0.8],
    { apti:null, dust:'L', bio:0.15, roles:['shade','edible'],
      note:'Shade-floor cover from plains to hills.' }),
  SP('ground','kanshira','Commelina benghalensis','কানশিরা (Kanshira)','Benghal dayflower','Commelinaceae','native',
    [0.7,0.85,0.4,5.0,7.5,0.7,0,1.5,0.5,0.4],
    { apti:null, dust:'L', bio:0.4, roles:['shade','wetland'],
      note:'Succulent shade cover of damp orchard floors.' }),
  SP('ground','chhagalkuri','Ipomoea pes-caprae','ছাগলখুরি (Chhagalkuri)','Beach morning glory','Convolvulaceae','native',
    [0.5,1.0,0.9,6.0,8.5,0.3,0,15,0.7,0.2],
    { apti:null, dust:'L', bio:0.5, roles:['dune','coastal','embankment'],
      note:'Primary dune binder of Digha and Sagar; runners root at every node.' }),
  SP('ground','jadupalang','Sesuvium portulacastrum','জাদু পালং (Jadu palang)','Sea purslane','Aizoaceae','native',
    [0.9,1.0,0.7,6.0,9.0,0.9,1,40,0.5,0.2],
    { apti:null, dust:'L', bio:0.6, roles:['saline','coastal','embankment','edible'],
      note:'Succulent halophyte mat for saline mudflats and embankment slopes.' }),
  SP('ground','spinifex','Spinifex littoreus','সমুদ্র ঘাস (Samudra ghas)','Beach spinifex','Poaceae','native',
    [0.4,1.0,1.0,6.0,8.5,0.2,0,15,0.8,0.2],
    { apti:null, dust:'L', bio:0.7, roles:['dune','coastal'],
      note:'Spiny fore-dune grass; first line of the coast.' }),
  SP('ground','dhanighas','Porteresia coarctata','ধানি ঘাস (Dhani ghas)','Wild rice grass','Poaceae','native',
    [1.0,0.9,0.1,6.5,9.0,1.0,3,40,0.3,0.15],
    { apti:null, dust:null, bio:0.8, hab:'tidal', roles:['mangrove','saline','pioneer'],
      note:'Pioneer grass of accreting tidal mud ahead of the mangrove line.' }),
  SP('ground','giria','Suaeda maritima','গিরিয়া শাক (Giria sag)','Herbaceous seepweed','Amaranthaceae','native',
    [0.9,1.0,0.6,6.5,9.0,0.9,2,40,0.3,0.3],
    { apti:null, dust:null, bio:0.4, roles:['saline','coastal','edible'],
      note:'Annual halophyte of salt pans and creek edges.' }),
  SP('ground','salineturf','Paspalum vaginatum','লবণ ঘাস (Lobon ghas)','Seashore paspalum','Poaceae','native',
    [0.9,1.0,0.6,5.5,9.0,0.9,0,20,0.5,0.4],
    { apti:null, dust:'M', bio:0.6, roles:['turf','saline','coastal','wetland'],
      note:'Salt-marsh turf that mows; the lawn for Sundarbans and Haldia.' }),
  SP('ground','ulu','Imperata cylindrica','উলু (Ulu)','Cogon grass, Thatch grass','Poaceae','native',
    [0.6,1.0,1.0,4.0,8.0,0.4,0,3,0.8,0.6],
    { apti:[13,11,15], dust:'M', bio:1.2, roles:['slope','drought','thatch'],
      note:'Rhizomatous cover for cut slopes and spoil; aggressive, use where nothing else holds.' }),
  SP('ground','speargrass','Heteropogon contortus','খড় ঘাস (Khor ghas)','Spear grass','Poaceae','native',
    [0.2,1.0,1.0,5.0,7.8,0.1,0,2,0.9,0.5],
    { apti:null, dust:'L', bio:0.8, roles:['drought','laterite','slope','fodder'],
      note:'Dry laterite grassland dominant.' }),
  SP('ground','chorkanta','Chrysopogon aciculatus','চোরকাঁটা (Chorkanta)','Love grass, Mackie\'s pest','Poaceae','native',
    [0.5,0.9,0.8,5.0,7.8,0.4,0,2,0.7,0.5],
    { apti:null, dust:'L', bio:0.4, roles:['turf','drought','shade'],
      note:'Village-lawn grass tolerating shade, trampling and drought.' }),
  SP('ground','talmuli','Curculigo orchioides','তালমূলী (Talmuli)','Golden eye-grass','Hypoxidaceae','native',
    [0.3,0.9,0.8,5.0,7.5,0.2,0,1,0.7,0.4],
    { apti:null, dust:'L', bio:0.2, roles:['shade','laterite','medicinal'],
      note:'Tuberous shade herb of Sal forest floors.' }),
  SP('ground','bhuichampa','Kaempferia rotunda','ভুঁই চাঁপা (Bhui champa)','Peacock ginger','Zingiberaceae','native',
    [0.5,0.85,0.6,5.5,7.5,0.5,0,1,0.4,0.4],
    { apti:null, dust:'L', bio:0.3, roles:['shade','ornamental','monsoon'],
      note:'Dormant in the dry season, emerges with the rains under canopy.' }),
  SP('ground','keu','Costus speciosus','কেউ (Keu)','Crepe ginger','Costaceae','native',
    [0.8,0.8,0.4,5.0,7.5,0.8,0,1.5,0.4,0.3],
    { apti:null, dust:'L', bio:1.0, roles:['shade','wetland','ornamental','medicinal'],
      note:'Tall rhizomatous herb for shaded wet edges.' }),
  SP('ground','kochu','Colocasia esculenta','কচু (Kochu)','Taro','Araceae','native',
    [1.0,0.85,0.2,5.5,7.5,1.0,0,1.5,0.3,0.3],
    { apti:null, dust:'L', bio:1.5, roles:['wetland','edible','shade','basin'],
      note:'Basin floor and drain-edge cover with food value.' }),
  SP('ground','basketgrass','Oplismenus compositus','ছায়া ঘাস (Chhaya ghas)','Running mountain grass','Poaceae','native',
    [0.6,0.8,0.4,5.0,7.5,0.5,0,1,0.6,0.5],
    { apti:null, dust:'L', bio:0.3, roles:['shade','turf'],
      note:'Deep-shade grass under closed canopy.' }),
  SP('ground','sanjeevani','Selaginella bryopteris','সঞ্জীবনী (Sanjeevani)','Spikemoss','Selaginellaceae','native',
    [0.4,0.2,0.6,4.5,6.5,0.3,0,0.3,0.9,0.8],
    { apti:null, dust:'L', bio:0.2, roles:['shade','slope','rock'],
      note:'Rock-face and shaded slope cover of the hills and Ayodhya scarps.' }),
  SP('ground','ophiopogon','Ophiopogon intermedius','হিমালয়ী মন্ডো (Himalayi mondo)','Himalayan lilyturf','Asparagaceae','native',
    [0.3,0.2,0.5,4.5,6.5,0.3,0,0.3,0.8,1.0],
    { apti:null, dust:'L', bio:0.3, roles:['shade','slope','ornamental'],
      note:'Evergreen tufted cover under hill forest.' }),
  SP('ground','bhuiainselu','Fragaria nubicola','ভুঁই ঐসেলু (Bhui ainselu)','Himalayan strawberry','Rosaceae','native',
    [0.3,0.05,0.5,4.5,6.5,0.3,0,0.3,0.9,1.0],
    { apti:null, dust:'L', bio:0.2, roles:['slope','edible','ornamental'],
      note:'Runner-forming cover on hill terraces and banks.' }),
  SP('ground','viola','Viola pilosa','হিমালয়ী ভায়োলা (Himalayi viola)','Himalayan violet','Violaceae','native',
    [0.3,0.05,0.4,4.5,6.5,0.3,0,0.3,0.8,1.0],
    { apti:null, dust:'L', bio:0.1, roles:['shade','slope'],
      note:'Shaded hill understory floor.' }),
  SP('ground','pinkknotweed','Persicaria capitata','পাহাড়ি পাথরচূর (Pahari patharchur)','Pink knotweed','Polygonaceae','native',
    [0.6,0.15,0.6,4.5,7.0,0.6,0,0.5,1.0,1.0],
    { apti:null, dust:'L', bio:0.3, roles:['slope','wall','ornamental'],
      note:'Cascading cover for hill retaining walls and cut slopes.' }),
  SP('ground','malingo','Arundinaria maling','মালিঙ্গো (Malingo)','Maling dwarf bamboo','Poaceae','native',
    [0.4,0.1,0.6,4.5,6.5,0.4,0,0.3,1.0,1.0],
    { apti:null, dust:'M', bio:2.5, roles:['slope','landslide','livelihood'],
      note:'Rhizomatous dwarf bamboo that stitches hill slopes together.' }),
  SP('ground','unyu','Dryopteris and Pteris ferns','উন্যু (Unyu)','Hill and terai ferns','Dryopteridaceae','native',
    [0.6,0.35,0.3,4.5,6.8,0.6,0,0.5,0.8,0.8],
    { apti:null, dust:'L', bio:0.4, roles:['shade','slope','wetland'],
      note:'Fern carpet for shaded humid slopes and stream banks.' }),
  /* exotics kept for screening */
  SP('ground','wedelia','Sphagneticola trilobata','ওয়েডেলিয়া (Wedelia)','Singapore daisy','Asteraceae','exotic',
    [0.8,1.0,0.8,5.0,8.5,0.7,0,3,0.6,0.4],
    { apti:[16,14,18], dust:'M', bio:0.5, roles:['invasive'],
      note:'Screened out: listed invasive smothering native ground flora.' }),
  SP('ground','tridax','Tridax procumbens','ত্রিধারা (Tridhara)','Coat buttons','Asteraceae','exotic',
    [0.3,1.0,1.0,5.5,8.5,0.2,0,3,0.7,0.4],
    { apti:[15,13,17], dust:'L', bio:0.2, roles:['invasive'],
      note:'Screened out: exotic wasteland weed.' })
];

/* Agro-climatic zones where each species is characteristic of the regional
   flora. Used only as a ranking tiebreaker among equal SSI, never as a filter. */
const ZONE_AFFINITY = {
  hijal:['newall','coast','oldall'], arjun:['newall','later','oldall','terai'], karanja:['newall','coast'], jam:['newall','later','oldall','terai'],
  kadam:['newall','terai','oldall'], chhatim:['newall','terai'], bot:['newall','later','oldall'], peepal:['newall','later','oldall'], dumur:['newall','terai','oldall'],
  neem:['later','newall','oldall'], mahua:['later'], sal:['later','terai'], palash:['later'], shimul:['newall','terai','later'], bahera:['later','terai'], haritaki:['later'],
  amloki:['later','newall'], bel:['later','newall','oldall'], aam:['newall','oldall'], kanthal:['newall','oldall'], tetul:['later','newall'], sissoo:['terai','oldall','newall'],
  gab:['newall','coast'], jarul:['newall','coast'], ashok:['newall'], bakul:['newall'], champa:['terai','hill'], sheora:['newall','later','oldall'], pitali:['newall','coast','terai'],
  barun:['newall','coast'], debdaru:['newall'], putranjiva:['newall','later'], sonalu:['later','newall'], chirol:['later','newall'], sirish:['later','newall','coast'],
  koroi:['newall','terai'], mandar:['coast','newall'], gamar:['terai'], paras:['coast'], dhaura:['later'], piyal:['later'], kusum:['later'], hollock:['terai'], lampati:['terai'],
  kainjal:['terai','hill'], utis:['hill'], chilauni:['hill','terai'], buk:['hill'], gurans:['hill'], ghogechanp:['hill'], paiyun:['hill'], katus:['hill'], saur:['hill'],
  sundari:['coast'], keora:['coast'], bain:['coast'], genwa:['coast'], kankra:['coast'], jhau:['coast'],
  shiuli:['newall','oldall'], kamini:['newall'], rangan:['newall'], joba:['newall'], akanda:['later','newall','coast'], bhant:['newall','terai','oldall'], bonjui:['coast','newall'],
  nishinda:['newall','later','oldall'], basak:['newall','oldall'], mehendi:['later','newall'], dhataki:['later','hill'], shiakul:['later'], karamcha:['later','newall'], baichi:['later'],
  belphul:['newall'], tagar:['newall'], gandharaj:['newall','terai'], kantajati:['later'], chita:['later','newall'], keya:['coast'], goran:['coast'], khalsi:['coast'], hargoza:['coast'],
  jayanti:['newall','coast'], phutki:['terai','hill'], argeli:['hill'], chutro:['hill'], mahonia:['hill'], aiselu:['hill'], asare:['hill'], kurchi:['later'], antamora:['later'],
  ulatkambal:['newall','terai'], ashsheora:['newall','oldall','terai'], panjuli:['newall','oldall'],
  durba:['newall','later','oldall','coast'], carpetgrass:['newall','terai'], manila:['coast'], vetiver:['newall','later','coast','oldall','terai'], thankuni:['newall','terai','oldall'],
  brahmi:['newall','coast'], kalmi:['newall','oldall'], sushni:['newall','oldall'], kulekhara:['newall','oldall'], sanchi:['newall','oldall'], kesut:['newall'], bhuiokra:['newall','coast','later'],
  kudaliya:['newall','later'], shankhapushpi:['later'], amrul:['newall','hill','terai'], kanshira:['newall','terai'], chhagalkuri:['coast'], jadupalang:['coast'], spinifex:['coast'],
  dhanighas:['coast'], giria:['coast'], salineturf:['coast'], ulu:['later','terai'], speargrass:['later'], chorkanta:['newall','later'], talmuli:['later'], bhuichampa:['newall','later'],
  keu:['newall','terai'], kochu:['newall','oldall'], basketgrass:['newall','terai'], sanjeevani:['hill','later'], ophiopogon:['hill'], bhuiainselu:['hill'], viola:['hill'],
  pinkknotweed:['hill'], malingo:['hill'], unyu:['hill','terai']
};
SPECIES.forEach(sp => { sp.zones = ZONE_AFFINITY[sp.id] || []; });
